name: goreleaser

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser-reusable:
    uses: esacteksab/.github/.github/workflows/go-release.yml@848feff4f2e6fa028d7f3dae9193dcc1129a16e5  # v0.87.9
