name: goreleaser

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser-reusable:
    uses: esacteksab/.github/.github/workflows/go-release.yml@d5a11bbf38654461e69040c3747acb4d1b93a219  # v0.80.7
