name: Pre-Commit

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SKIP: ${{ vars.SKIP }}

permissions:
  contents: read

jobs:
  precommit-reusable:
    uses: esacteksab/.github/.github/workflows/pre-commit.yml@d5a11bbf38654461e69040c3747acb4d1b93a219  # v0.80.7
